import { orangeColors, zincColors, seanceColors } from '../style';

export const lightTheme = {
  token: {
    colorPrimary: orangeColors[400],
    colorBgBase: zincColors[100],
    colorTextBase: zincColors[600],
    fontSize: 16,
    titleColor: orangeColors[400],
  },
  components: {
    Typography: {
      colorTextHeading: orangeColors[400],
      colorTextDescription: orangeColors[300],
      colorLink: orangeColors[400],
      colorLinkActive: orangeColors[500],
      colorLinkHover: orangeColors[500],
      fontSizeHeading1: 64,
      fontSizeHeading2: 50,
      titleMarginBottom: 10,
      titleMarginTop: 0,
      fontWeightStrong: 600,
    },
    Layout: {
      headerBg: seanceColors[100],
      footerBg: seanceColors[100],
      headerPadding: '0px 25px',
      footerPadding: '20px 25px',
      bodyBg: `linear-gradient(45deg, ${seanceColors[200]}, ${seanceColors[300]})`,
    },
    Select: {
      activeOutlineColor: 'none',
      colorText: orangeColors[400],
      colorTextQuaternary: orangeColors[400],
      optionActiveBg: zincColors[200],
      optionSelectedColor: orangeColors[400],
      optionSelectedBg: zincColors[100],
      colorBorder: orangeColors[400],
      colorBgElevated: zincColors[50],
    },
    Dropdown: {
      colorBgElevated: zincColors[100],
      colorText: orangeColors[400],
      controlItemBgHover: zincColors[300],
    },
    Button: {
      colorPrimary: `linear-gradient(45deg, ${orangeColors[300]}, ${orangeColors[500]})`,
      colorPrimaryActive: `linear-gradient(45deg, ${orangeColors[400]}, ${orangeColors[600]})`,
      colorPrimaryHover: `linear-gradient(45deg, ${orangeColors[400]}, ${orangeColors[600]})`,
      defaultBg: 'transparent',
      defaultHoverBg: 'transparent',
      defaultActiveBg: 'transparent',
      defaultBorderColor: orangeColors[400],
      defaultHoverBorderColor: orangeColors[500],
      defaultColor: orangeColors[400],
      defaultHoverColor: orangeColors[500],
      primaryShadow: '0',
      borderRadius: 25,
      borderRadiusLG: 25,
      borderRadiusSM: 25,
      controlHeightSM: 33,
      paddingInlineSM: 15,
      controlHeight: 40,
      paddingInline: 15,
      contentFontSize: 18,
      contentFontSizeLG: 25,
      paddingInlineLG: 40,
      controlHeightLG: 45,
    },
    Drawer: {
      colorIcon: orangeColors[700],
      colorIconHover: orangeColors[400],
    },
    Tooltip: {
      colorBgSpotlight: seanceColors[50],
      colorTextLightSolid: orangeColors[700],
    },
    Divider: {
      colorSplit: orangeColors[400],
    },
    Card: {
      colorBgContainer: seanceColors[100],
      headerHeight: 70,
      colorBorderSecondary: 'transparent',
    },
    Input: {
      activeShadow: '0',
      errorActiveShadow: '0',
    },
  },
};

export const darkTheme = {
  token: {
    colorPrimary: orangeColors[400],
    colorBgBase: zincColors[800],
    colorTextBase: orangeColors[100],
    fontSize: 16,
    titleColor: orangeColors[400],
  },
  components: {
    Typography: {
      colorTextHeading: orangeColors[400],
      colorTextDescription: orangeColors[100],
      colorLink: orangeColors[400],
      colorLinkActive: orangeColors[500],
      colorLinkHover: orangeColors[500],
      fontSizeHeading1: 64,
      fontSizeHeading2: 50,
      titleMarginBottom: 10,
      titleMarginTop: 0,
      fontWeightStrong: 600,
    },
    Layout: {
      headerBg: zincColors[800],
      headerPadding: '0px 25px',
      footerPadding: '20px 25px',
      footerBg: zincColors[800],
      bodyBg: `linear-gradient(45deg, ${zincColors[700]}, ${zincColors[900]})`,
    },
    Select: {
      activeOutlineColor: 'none',
      colorText: orangeColors[400],
      colorTextQuaternary: orangeColors[400],
      optionActiveBg: zincColors[500],
      optionSelectedColor: orangeColors[400],
      optionSelectedBg: zincColors[700],
      colorBorder: orangeColors[400],
      colorBgElevated: zincColors[600],
    },
    Dropdown: {
      colorBgElevated: zincColors[600],
      colorText: orangeColors[400],
      controlItemBgHover: zincColors[500],
    },
    Tooltip: {
      colorBgSpotlight: zincColors[600],
      colorTextLightSolid: orangeColors[500],
    },
    Button: {
      colorPrimary: `linear-gradient(45deg, ${orangeColors[300]}, ${orangeColors[500]})`,
      colorPrimaryActive: `linear-gradient(45deg, ${orangeColors[400]}, ${orangeColors[600]})`,
      colorPrimaryHover: `linear-gradient(45deg, ${orangeColors[400]}, ${orangeColors[600]})`,
      primaryBorderColor: zincColors[600],
      primaryHoverBorderColor: orangeColors[600],
      defaultBg: 'transparent',
      defaultHoverBg: 'transparent',
      defaultActiveBg: 'transparent',
      defaultBorderColor: orangeColors[400],
      defaultHoverBorderColor: orangeColors[500],
      defaultColor: orangeColors[400],
      defaultHoverColor: orangeColors[500],
      primaryShadow: '0',
      borderRadius: 25,
      borderRadiusSM: 25,
      borderRadiusLG: 25,
      controlHeightSM: 33,
      paddingInlineSM: 15,
      controlHeight: 40,
      paddingInline: 15,
      contentFontSize: 18,
      contentFontSizeLG: 25,
      paddingInlineLG: 40,
      controlHeightLG: 45,
    },
    Drawer: {
      colorIcon: orangeColors[500],
      colorIconHover: orangeColors[400],
    },
    Divider: {
      colorSplit: zincColors[500],
    },
    Card: {
      colorBgContainer: zincColors[900],
      headerHeight: 70,
      colorBorderSecondary: 'transparent',
    },
    Input: {
      activeShadow: '0',
      errorActiveShadow: '0',
    },
  },
};
